<?php
/* @var $form \Application\Form\User\Login */
?>
<form action="<?= $this->getHelper('url')('login') ?>" method="POST" class="p-3 js-form">
    <div class="form-group">
        <label for="element_email">Email</label>
        <input name="email" type="text" class="form-control" id="element_email" placeholder="name@example.com"
               value="<?= $form->getValue('email') ?>">
    </div>
    <div class="form-group">
        <label for="element_password">Password</label>
        <input name="password" type="text" class="form-control" id="element_password" value="">
    </div>
    <?php if (!empty($errors)) { ?>
        <?php foreach ($errors as $errorMessage) { ?>
            <div class="alert alert-danger" role="alert">
                <?= $errorMessage ?>
            </div>
        <?php } ?>
    <?php } ?>
    <button type="submit" class="btn btn-primary m-3">Войти</button>
</form>